"""agregar tabla categorias

Revision ID: af511b3d0ae3
Revises: ee3ed58733e7
Create Date: 2026-07-05 00:31:18.915647

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'af511b3d0ae3'
down_revision = 'ee3ed58733e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('detalle_pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('estado', sa.Enum('pendiente', 'pagado', 'enviado', 'entregado', 'cancelado'), nullable=True))
        batch_op.add_column(sa.Column('direccion', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('notas', sa.Text(), nullable=True))
        batch_op.alter_column('total',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('1'), type_='foreignkey')
        batch_op.drop_column('cantidad')
        batch_op.drop_column('producto_id')

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagen', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('activo', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('creado_en', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('categoria_id', sa.Integer(), nullable=False))
        batch_op.alter_column('nombre',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('precio',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'categorias', ['categoria_id'], ['id'])

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rol', sa.Enum('cliente', 'admin'), nullable=True))
        batch_op.add_column(sa.Column('activo', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('creado_en', sa.DateTime(), nullable=True))
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=256),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('creado_en')
        batch_op.drop_column('activo')
        batch_op.drop_column('rol')

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('precio',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('nombre',
               existing_type=sa.String(length=150),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('categoria_id')
        batch_op.drop_column('creado_en')
        batch_op.drop_column('activo')
        batch_op.drop_column('imagen')

    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('producto_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('cantidad', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('1'), 'productos', ['producto_id'], ['id'])
        batch_op.alter_column('total',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.FLOAT(),
               nullable=False)
        batch_op.drop_column('notas')
        batch_op.drop_column('direccion')
        batch_op.drop_column('estado')
        batch_op.drop_column('fecha')

    op.drop_table('detalle_pedido')
    op.drop_table('categorias')
    # ### end Alembic commands ###
